let D=[],cv=document.getElementById('map'),ctx=cv.getContext('2d'),layer=document.getElementById('layer'),info=document.getElementById('info'),status=document.getElementById('status');let W,H,dpr=1,s=1,ox=0,oy=0,drag=false,lx=0,ly=0,xmin,xmax,ymin,ymax;
function hash(v){v=String(v??'');let h=2166136261;for(let i=0;i<v.length;i++){h^=v.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function color(o){let v=o[layer.value];if(layer.value==='height'){let n=+v,t=Math.max(0,Math.min(1,(n-20)/80));return `hsl(${120-105*t} 60% 45%)`}return `hsl(${hash(v)%360} 58% 45%)`}
function fit(){s=Math.min(W/(xmax-xmin),H/(ymax-ymin))*.91;ox=(W-(xmax-xmin)*s)/2-xmin*s;oy=(H-(ymax-ymin)*s)/2+ymax*s;draw()}
function px(x){return x*s+ox}function py(y){return-y*s+oy}
function draw(){ctx.fillStyle='#9fc5d8';ctx.fillRect(0,0,W,H);let shown=0,r=Math.max(1.2,Math.min(5,s*2));for(let o of D){let x=px(+o.xMiles),y=py(+o.yMiles);if(x<-4||x>W+4||y<-4||y>H+4)continue;ctx.fillStyle=color(o);ctx.fillRect(x-r/2,y-r/2,r,r);shown++}status.textContent=`${shown.toLocaleString()} visible / ${D.length.toLocaleString()} authoritative large land cells`}
function resize(){W=innerWidth;H=innerHeight;dpr=Math.min(devicePixelRatio||1,2);cv.width=W*dpr;cv.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);draw()}
function inspect(o){info.innerHTML='<b>Selected authoritative large cell</b><table>'+Object.entries(o).map(([k,v])=>`<tr><td>${k}</td><td>${typeof v==='object'?JSON.stringify(v):String(v??'')}</td></tr>`).join('')+'</table>';info.style.display='block'}
function nearest(ex,ey){let best=null,bd=1e99;for(let o of D){let dx=px(+o.xMiles)-ex,dy=py(+o.yMiles)-ey,d=dx*dx+dy*dy;if(d<bd){bd=d;best=o}}if(best)inspect(best)}
cv.onpointerdown=e=>{drag=true;lx=e.clientX;ly=e.clientY;cv.setPointerCapture(e.pointerId)};cv.onpointermove=e=>{if(drag){ox+=e.clientX-lx;oy+=e.clientY-ly;lx=e.clientX;ly=e.clientY;draw()}};cv.onpointerup=()=>drag=false;cv.ondblclick=e=>nearest(e.clientX,e.clientY);
cv.addEventListener('wheel',e=>{e.preventDefault();let k=Math.exp(-e.deltaY*.001),wx=(e.clientX-ox)/s,wy=(oy-e.clientY)/s;s*=k;ox=e.clientX-wx*s;oy=e.clientY+wy*s;draw()},{passive:false});layer.onchange=draw;document.getElementById('fit').onclick=fit;document.getElementById('go').onclick=()=>{let q=document.getElementById('search').value.toLowerCase();let o=D.find(x=>JSON.stringify(x).toLowerCase().includes(q));if(o){s=Math.max(s,8);ox=W/2-(+o.xMiles)*s;oy=H/2+(+o.yMiles)*s;inspect(o);draw()}};
fetch('large-cells.json').then(r=>{if(!r.ok)throw Error(r.status);return r.json()}).then(d=>{D=d;xmin=Math.min(...D.map(o=>+o.xMiles));xmax=Math.max(...D.map(o=>+o.xMiles));ymin=Math.min(...D.map(o=>+o.yMiles));ymax=Math.max(...D.map(o=>+o.yMiles));document.getElementById('loading').style.display='none';resize();fit()}).catch(e=>document.getElementById('loading').textContent='LOAD ERROR: '+e);
addEventListener('resize',resize);